// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szzxcqilpcmkdwhdleqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6enhjcWlscGNta2R3aGRsZXF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyOTkyMDIsImV4cCI6MjA1Nzg3NTIwMn0.duJ5CcLXZSOrLneN0viXYvw3qtcIHmyqyK79ZHLkG50";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);